### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by Jammie3d** [JammieDodgerr/Session_Template#1]
Template
- [ ] Install instructions
- [x] Better Miniramp
- [ ] Decal example
- [ ] PMAT examples (Dizzy's Map)
- [ ] Random spawn point blueprint example
- [ ] RMS Compatibility
- [x] Updated PMATs

Wiki
- [x] Complex collision note
- [x] PMAT Page
- [ ] Custom fog blueprint
- [ ] Update transition collision
- [ ] Shadow Two Sided in troubleshooting
- [ ] Gear Modding Section
- [x] Movable Objects
- [ ] Custom Moveable Objects
- [ ] How to add a bus stop
